#!/bin/bash

# Activate python virtual environment
source ~/venv/svislam-devel/bin/activate

# Include generated library in search path
export LD_LIBRARY_PATH=$HOME/code/svislam/csrc:$LD_LIBRARY_PATH

cd ~/code/svislam/examples

OPTS="--redirect_stdout --Nsamp=100 --lrate0_info=0.5 --lrate0=10 --saveskip=1"
python ngslam_lm.py @config/ngvi_manhattanOlson3500_lm.run $OPTS $@