#!/bin/bash

# Activate python virtual environment
source ~/venv/svislam-devel/bin/activate

# Include generated library in search path
export LD_LIBRARY_PATH=$HOME/code/svislam/csrc:$LD_LIBRARY_PATH

cd ~/code/svislam/examples

OPTS="--redirect_stdout --saveskip=1
      --Nsamp=150 --lrate0_info=0.5 --lrate0=10 --maxiter_cg=600"
python ngslam_lm.py @config/ngvi_m3500_smallinfo_lm.run $OPTS $@
