#!/bin/bash

tf_initial=50
tf_num=3
tf_base=2
reps=100
transient_cutoff=100

cases="steady-state transient sk-21 sk-51 sk-101 sk-201"

BASEOPTS="--jax-x64 --jax-platform=cpu --optimizer=deterministic"
TARGET="sbatch duffing-vsi-run"

DATADIR=$(date "+$HOME/data/duffing_%F_%Hh%Mm%Ss")
mkdir -p $DATADIR

for case in $cases ; do
    for (( i=0 ; i<$tf_num ; i++ )); do 
        tf=$(bc <<< "$tf_base^$i*$tf_initial")

        if [ "$case" == "transient" ]; then
            if (( tf > transient_cutoff )); then
                continue
            fi
        fi

        SUBDIR="$case/tf_$tf"
        mkdir -p $DATADIR/$SUBDIR
        cd $DATADIR/$SUBDIR

        for (( seedsim=0 ; seedsim<$reps ; seedsim++ )) ;  do
            if [[ $case == sk-* ]] ; then
                PROBLEM="smoother-kernel"
                NWIN=$(echo $case | cut -b 4-)
            else
                PROBLEM=$case
                NWIN=1
            fi

            OPTS="--tf=$tf --seedsim=$seedsim --nwin=$NWIN --problem=$PROBLEM
                  --pickleout=$seedsim.pickle --txtout=$seedsim.txt"
            
            $TARGET $BASEOPTS $OPTS $@
        done
    done
done
