#!/bin/bash

tf_initial=50
tf_num=4
reps=10

cases="steady-state transient sk-21 sk-51 sk-101"

tf_num=1
reps=1
cases="steady-state"

BASEOPTS="--jax-x64 --jax-platform=cpu --optimizer=deterministic"
TARGET="sbatch duffing-vsi-run"

DATADIR=$(date "+$HOME/data/duffing_%F_%Hh%Mm%Ss")
mkdir -p $DATADIR

for case in $cases ; do
    for (( i=0 ; i<$tf_num ; i++ )); do 
        let "tf = $tf_initial * 2 ** $i"

        SUBDIR="$case/tf_$tf"
        mkdir -p $DATADIR/$SUBDIR
        cd $DATADIR/$SUBDIR

        for (( seedsim=0 ; seedsim<$reps ; seedsim++ )) ;  do
            if [[ $case == sk-* ]] ; then
                PROBLEM="smoother-kernel"
                NWIN=$(echo $case | cut -b 4-)
            else
                PROBLEM=$case
                NWIN=1
            fi

            OPTS="--tf=$tf --seedsim=$seedsim --nwin=$NWIN --problem=$PROBLEM
                  --output=$seedsim.pickle"
            
            $TARGET $BASEOPTS $OPTS $@
        done
    done
done
