#!/bin/bash

# Job submission parameters
NX_BASE=5
NU_BASE=2
NY_BASE=2
MUL_END=4
REPS=10
LRATE_BASE=0.1

# Parameters of the job run script
BASEOPTS="--N=1000 --Nbatch=1000 --epochs=50"
BASESBATCHOPTS="-p comm_small_day"
SCRIPT="linsys-vsi-run"

# Create directories
DIRNAME=$(date "+linsys_%F_%Hh%Mm%Ss")
DATADIR="$HOME/data/$DIRNAME"
SCRATCHDIR="$HOME/scratch/data/$DIRNAME"
mkdir -p $DATADIR
mkdir -p $SCRATCHDIR

# Change to the data directory
cd $DATADIR

# Iterate over the cases
for (( MUL=1 ; MUL<=MUL_END ; MUL=MUL*2 )); do 

    # Determine model dimensions
    NX=$(( NX_BASE*MUL ))
    NY=$(( NY_BASE*MUL ))
    NU=$(( NU_BASE*MUL ))
    LRATE0=$(bc -l <<< "$LRATE_BASE / $MUL^2")

    for (( SEED=0 ; SEED<$REPS ; SEED++ )) ;  do
        ID="$MUL-$SEED"

        OPTS="--nx=$NX --nu=$NU --ny=$NY --seed=$SEED --lrate0=$LRATE0 
              --savemat=$SCRATCHDIR/$ID.mat --pickleout=$SCRATCHDIR/$ID.pickle
              --txtout=$ID.txt"
        
        SBATCHOPTS="--job-name=$ID"
        sbatch $SBATCHOPTS $BASESBATCHOPTS $SCRIPT $BASEOPTS $OPTS
    done
done
