#!/bin/bash

# Job submission parameters
NX_BASE=5
NU_BASE=2
NY_BASE=2
MUL_END=16
REPS=10
LRATE0=0.005
TRANSITION_STEPS=2000
MAX_POLE_RADIUS=0.95

# Parameters of the job run script
BASEOPTS="--N=1000 --Nbatch=1000 --epochs=50"
BASESBATCHOPTS="-p comm_gpu_inter -G 1"
SCRIPT="linsys-vsi-run"

# Create directories
DIRNAME=$(date "+linsys_%F_%Hh%Mm%Ss")
DATADIR="$HOME/data/$DIRNAME"
SCRATCHDIR="$HOME/scratch/data/$DIRNAME"
mkdir -p $DATADIR
mkdir -p $SCRATCHDIR
cp $0 $DATADIR/
cp $0 $SCRATCHDIR/

# Change to the data directory
cd $DATADIR
echo Result dir: $DIRNAME

# Iterate over the cases
for (( MUL=1 ; MUL<=MUL_END ; MUL=MUL*2 )); do 

    # Determine model dimensions
    NX=$(( NX_BASE*MUL ))
    NY=$(( NY_BASE*MUL ))
    NU=$(( NU_BASE*MUL ))

    for (( SEED=0 ; SEED<$REPS ; SEED++ )) ;  do
        ID="$MUL-$SEED"

        OPTS="--nx=$NX --nu=$NU --ny=$NY --seed=$SEED --lrate0=$LRATE0
              --max_pole_radius=$MAX_POLE_RADIUS 
              --transition_steps=$TRANSITION_STEPS
              --savemat=$SCRATCHDIR/$ID.mat --pickleout=$SCRATCHDIR/$ID.pickle
              --txtout=$ID.txt"
        
        SBATCHOPTS="--job-name=$ID"
        sbatch $SBATCHOPTS $BASESBATCHOPTS $SCRIPT $BASEOPTS $OPTS
    done
done
