#!/bin/bash

# Job submission parameters
let NX=5*4
let NU=2*4
let NY=2*4
REPS=3
LRATE0=1e-2

# Parameters of the job run script
BASEOPTS="--N=1000 --Nbatch=1000 --epochs=50"
BASESBATCHOPTS="-p standby"
SCRIPT="linsys-vsi-run"

# Create directories
DIRNAME=$(date "+linsys_test_%F_%Hh%Mm%Ss")
DATADIR="$HOME/data/$DIRNAME"
SCRATCHDIR="$HOME/scratch/data/$DIRNAME"
mkdir -p $DATADIR
mkdir -p $SCRATCHDIR

# Change to the data directory
cd $DATADIR

for (( SEED=0 ; SEED<$REPS ; SEED++ )) ;  do
    ID="$SEED"

    OPTS="--nx=$NX --nu=$NU --ny=$NY --seed=$SEED --lrate0=$LRATE0
          --pickleout=$SCRATCHDIR/$ID.pickle --txtout=$ID.txt"
    
    SBATCHOPTS="--job-name=$ID"
    sbatch $SBATCHOPTS $BASESBATCHOPTS $SCRIPT $BASEOPTS $OPTS
done
