#!/bin/bash

# Job submission parameters
NX_BASE=5
NU_BASE=2
NY_BASE=2
MUL_END=8
REPS=10

# Parameters of the job run script
BASEOPTS="--N=1000 --Nbatch=1000 --epochs=50"
BASESBATCHOPTS="-p standby"
SCRIPT="linsys-vsi-run"

# Create directories
DIRNAME=$(date "+linsys_%F_%Hh%Mm%Ss")
DATADIR="$HOME/data/$DIRNAME"
SCRATCHDIR="$HOME/scratch/data/$DIRNAME"
mkdir -p $DATADIR
mkdir -p $SCRATCHDIR

# Change to the data directory
cd $DATADIR

# Iterate over the cases
for (( MUL=1 ; MUL<=MUL_END ; MUL=MUL*2 )); do 

    # Determine model dimensions
    NX=$(( NX_BASE*MUL ))
    NY=$(( NY_BASE*MUL ))
    NU=$(( NU_BASE*MUL ))

    for (( SEED=0 ; SEED<$REPS ; SEED++ )) ;  do
        ID=$MUL-$SEED

        OPTS="--nx=$NX --nu=$NU --ny=$NY --seed=$SEED
              --savemat=$SCRATCHDIR/$ID.mat --txtout=$ID.txt"
        
        SBATCHOPTS="--output=$ID.%j.out --job-name=$ID"
        sbatch $SBATCHOPTS $BASESBATCHOPTS $SCRIPT $BASEOPTS $OPTS
    done
done
